const REQUEST = 0x01;
const RESPONSE = 0x02;
const STREAM_START = 0x03;
const STREAM_DATA = 0x04;
const STREAM_END = 0x05;
const ERROR = 0x06;
const PING = 0x07;
const PONG = 0x08;
const BROADCAST = 0x09;
const SUBSCRIBE = 0x0A;
const UNSUBSCRIBE = 0x0B;
const PUBLISH = 0x0C;
const CLOSE = 0x0D;
const CLOSE_ACK = 0x0E;
const HELLO = 0x0F;
const HELLO_ACK = 0x10;
const SERVER_CLOSING = 0x11;
const ROUTE_REQUEST = 0x12;  // v2 only
const PRIORITY_ACK = 0x13;   // v2 only

const FLAGS = {
  COMPRESSED:      0x01,  // Bit 0
  ENCRYPTED:       0x02,  // Bit 1
  PRIORITY_SET:    0x04,  // Bit 2
  HAS_ROUTING_KEY: 0x08,  // Bit 3
  FRAGMENTED:      0x10,  // Bit 4
};

const PRIORITY = {
  LOWEST: 0,
  LOW: 1,
  BELOW_NORMAL: 2,
  NORMAL: 3,
  ABOVE_NORMAL: 4,
  HIGH: 5,
  CRITICAL: 6,
  REAL_TIME: 7,
};

const PROTOCOL_VERSION = {
  V1: 0x01,
  V2: 0x02,
};

const FRAME_TYPE_NAMES = {
  [REQUEST]: 'REQUEST',
  [RESPONSE]: 'RESPONSE',
  [STREAM_START]: 'STREAM_START',
  [STREAM_DATA]: 'STREAM_DATA',
  [STREAM_END]: 'STREAM_END',
  [ERROR]: 'ERROR',
  [PING]: 'PING',
  [PONG]: 'PONG',
  [BROADCAST]: 'BROADCAST',
  [SUBSCRIBE]: 'SUBSCRIBE',
  [UNSUBSCRIBE]: 'UNSUBSCRIBE',
  [PUBLISH]: 'PUBLISH',
  [CLOSE]: 'CLOSE',
  [CLOSE_ACK]: 'CLOSE_ACK',
  [HELLO]: 'HELLO',
  [HELLO_ACK]: 'HELLO_ACK',
  [SERVER_CLOSING]: 'SERVER_CLOSING',
  [ROUTE_REQUEST]: 'ROUTE_REQUEST',
  [PRIORITY_ACK]: 'PRIORITY_ACK',
};

module.exports = {
  REQUEST,
  RESPONSE,
  STREAM_START,
  STREAM_DATA,
  STREAM_END,
  ERROR,
  PING,
  PONG,
  BROADCAST,
  SUBSCRIBE,
  UNSUBSCRIBE,
  PUBLISH,
  CLOSE,
  CLOSE_ACK,
  HELLO,
  HELLO_ACK,
  SERVER_CLOSING,
  ROUTE_REQUEST,
  PRIORITY_ACK,
  FLAGS,
  PRIORITY,
  PROTOCOL_VERSION,
  FRAME_TYPE_NAMES,
};
