const REQUEST = 0x01;
const RESPONSE = 0x02;
const STREAM_START = 0x03;
const STREAM_DATA = 0x04;
const STREAM_END = 0x05;
const ERROR = 0x06;
const PING = 0x07;
const PONG = 0x08;
const BROADCAST = 0x09;
const SUBSCRIBE = 0x0A;
const UNSUBSCRIBE = 0x0B;
const PUBLISH = 0x0C;
const CLOSE = 0x0D;
const CLOSE_ACK = 0x0E;
const HELLO = 0x0F;
const HELLO_ACK = 0x10;

const FLAGS = {
  COMPRESSED: 0b10000000,
  ENCRYPTED: 0b01000000,
  FINAL: 0b00100000,
  PRIORITY: 0b00010000,
  ACK_REQUIRED: 0b00001000,
};

const FRAME_TYPE_NAMES = {
  [REQUEST]: 'REQUEST',
  [RESPONSE]: 'RESPONSE',
  [STREAM_START]: 'STREAM_START',
  [STREAM_DATA]: 'STREAM_DATA',
  [STREAM_END]: 'STREAM_END',
  [ERROR]: 'ERROR',
  [PING]: 'PING',
  [PONG]: 'PONG',
  [BROADCAST]: 'BROADCAST',
  [SUBSCRIBE]: 'SUBSCRIBE',
  [UNSUBSCRIBE]: 'UNSUBSCRIBE',
  [PUBLISH]: 'PUBLISH',
  [CLOSE]: 'CLOSE',
  [CLOSE_ACK]: 'CLOSE_ACK',
  [HELLO]: 'HELLO',
  [HELLO_ACK]: 'HELLO_ACK',
};

module.exports = {
  REQUEST,
  RESPONSE,
  STREAM_START,
  STREAM_DATA,
  STREAM_END,
  ERROR,
  PING,
  PONG,
  BROADCAST,
  SUBSCRIBE,
  UNSUBSCRIBE,
  PUBLISH,
  CLOSE,
  CLOSE_ACK,
  HELLO,
  HELLO_ACK,
  FLAGS,
  FRAME_TYPE_NAMES,
};
